
[package]
name = "ikm-controller"
version = "0.1.0"
edition = "2024"
rust-version = "1.91"
license = "MIT OR Apache-2.0"
readme = "README.md"
exclude = [
  ".github",
  ".vscode",
  ".idea",
  ".git",
  ".roo",
  "docs/*",
  "tmp/*",
  ".gitattributes",
  ".gitignore",
  "pki",
]
#####################################

[profile.dist]
inherits = "release"
opt-level = 3

[profile.release]
panic = "abort"
opt-level = "s"
lto = "thin"
codegen-units = 1
incremental = false
debug = false
strip = "debuginfo"

[profile.dev]
panic = "abort"
incremental = true
lto = "off"
[profile.dev.package."*"]
opt-level = 3


#####################################
[dependencies]
#------------ utils ------------#
taxon-core = { path = "../taxon/crates/taxon_core", features = ["desktop"] }

fancy-regex = "0.16"
thiserror = "^1.0"
anyhow = "^1.0"
rand = { version = "0.8", default-features = false, features = [
  "serde",
  "alloc",
  "rand_chacha",
] }
xlsx-handlebars = "0.2.2"
#------------ data types ------------#
chrono = { version = "^0.4", default-features = false, features = [
  "serde",
  "clock",
  "wasmbind",
  "core-error",
  "pure-rust-locales",
] }
url = { version = "^2.5", features = ["serde"] }
uuid = { version = "^1.17", features = ["v4", "v5", "v7", "serde"] }
bytes = "1"
semver = { version = "^1", features = ["serde"] }
smol_str = { version = "0.2", features = ["serde", "arbitrary"] }

#------------ Parse/Serialize/Validate ------------#
serde = { version = "^1.0", features = ["derive", "rc"] }
serde-saphyr = "0.0.8"
saphyr = "0.0.6"
serde_json = { version = "^1.0", features = [
  "preserve_order",
  "arbitrary_precision",
  "raw_value",
] }
schemars = { version = "^1", features = [
  "chrono04",
  "url2",
  "uuid1",
  "smallvec1",
  "smol_str02",
  "semver1",
  "bytes1",
  "indexmap2",
  "raw_value",
  "preserve_order",
] }
#------------ async ------------#
tokio-util = { version = "^0.7" }
tokio = { version = "^1.44" }
futures = { version = "^0.3" }
ractor = { version = "0.15", default-features = false, features = [
  "async-trait",
  "message_span_propogation",
  "output-port-v2",
] }
futures-channel = "*"
futures-util = "*"
#------------ net ------------#
serialport = { version = "^4", features = ["serde"] }
tokio-serial = { version = "^5" }
#------------ cli ------------#
clap = { version = "^4.5", features = ["derive", "env"] }
#------------ tracing ------------#
tracing = { version = "^0.1", features = ["attributes", "valuable"] }
