devices:
  - port: "/dev/ttyUSB0"
    slave: 1
    addres: 11
    value: 111
  - port: "/dev/ttyUSB0"
    slave: 1
    addres: 2
    value: 222
  - port: "/dev/ttyUSB1"
    slave: 3
    addres: 3
    value: 333
  - port: "/dev/ttyUSB1"
    slave: 4
    addres: 4
    value: 444
