- type: Oil
  id: "00000000-0000-0000-0000-000000000001"
  title: "Oil-1"
  product_weight: null
  volume_at_15: null
  vapor_density_method: manual
  vapor_density: null

- type: OilProduct
  id: "00000000-0000-0000-0000-000000000002"
  title: "OilProduct-2"
  product_weight: null
  volume_at_15: null
  vapor_density_method: calculated
  initial_boiling_point: null
