- id: "00000000-0000-0000-0000-000000000001"
  ns: Product
  type: Oil
  title: "Oil-1"
  vapor:
    method: manual
    vapor_density: null

- id: "00000000-0000-0000-0000-000000000002"
  ns: Product
  type: OilProduct
  title: "OilProduct-2"
  vapor:
    method: calculated
    initial_boiling_point: null

