basic_data:
  name: Tank-3
  reservoir_park: Парк 1
  group: Группа 1
  tank_type: vertical
  nominal_capacity: "12070"
  density_stored_liquid_according: "738"
  basic_height: "12070"
  product: default oil
  maximum_allowable_product_level: "12070"
levels_of_point_sensors:
  hysteresis: "2"
  points:
    - id: T0
      index: 0
      value: 750
    - id: T1
      index: 1
      value: 2000
    - id: T2
      index: 2
      value: 3500
    - id: T3
      index: 3
      value: 5000
    - id: T4
      index: 4
      value: 6500
    - id: T5
      index: 5
      value: 8000
    - id: T6
      index: 6
      value: 9500
    - id: T7
      index: 7
      value: 11000
    - id: T8
      index: 8
      value: 12500
    - id: T9
      index: 9
      value: 15000
construction:
  linear_expansion: "0.0000125"
  mass_floating_coating: "2877"
mass_calculation_method:
  method: "1"
  switching_level: "3500"
  switching_level_hysteresis: "2"
  p3_p1: "12758"
  p1_reference_point: "1242"
  reference_point: "0"
measurement_accuracy_indicators:
  limit_permissible_absolute_error: "0.001"
  hydrostatic_device_limit: "110000"
  pressure_device_limit: "10000"
  limit_permissible_absolute_measurement_reservoir_level: "1"
  limit_permissible_absolute_measurement_level_raw_water: "1"
  limit_permissible_absolute_measurement_temp_products_and_vapours: "0.5"
  limit_permissible_absolute_measurement_oil_densities: "1"
  drawing_calibration_table: grad_table_v1
  hydrostatic_device_vpi: null
  pressure_device_vpi: null
calibration_block:
  level_coefficient: "-2"
  level_point_sensors:
    - id: T0
      index: 0
      value: 750
    - id: T1
      index: 1
      value: 2000
    - id: T2
      index: 2
      value: 3500
    - id: T3
      index: 3
      value: 5000
    - id: T4
      index: 4
      value: 6500
    - id: T5
      index: 5
      value: 8000
    - id: T6
      index: 6
      value: 9500
    - id: T7
      index: 7
      value: 11000
    - id: T8
      index: 8
      value: 12500
    - id: T9
      index: 9
      value: 15000
